Feature/pn 1772
pagopa/pn-delivery-push pull request #114
Opened 2022-07-22 09:17 UTC by simonerondinella

2022-07-28 10:03 UTC, fabriziolana requested changes

2022-07-28 10:03 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/GetLegalFactServiceImpl.java
>          PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
anche qui secondo me meglio metterlo nel costruttore

2022-07-28 10:03 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
>          PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
anche qui nel costruttore

2022-07-28 10:03 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java
>          PnAuditLogEvent logEvent = auditLogBuilder
costruttore

2022-08-01 15:54 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/DigitalWorkFlowHandler.java
> +        PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
Creato task apposito PN-1954

2022-08-01 15:54 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/DigitalWorkFlowHandler.java
> +            PnAuditLogEvent logEvent = auditLogBuilder
Creato task apposito PN-1954

2022-08-01 15:54 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
>          PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
Creato task apposito PN-1954

2022-08-01 15:54 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java
>          PnAuditLogEvent logEvent = auditLogBuilder
Creato task apposito PN-1954

2022-08-04 13:47 UTC, MTurraPpa approved these changes

2022-08-05 07:25 UTC, merged