F24 standard management #pn-1997
pagopa/pn-delivery-push pull request #136
Opened 2022-08-09 14:55 UTC by AndreaCimini90

2022-08-09 15:10 UTC, MTurraPpa reviewed
Riesci ad aggiungere un test?

2022-08-10 07:54 UTC, MTurraPpa requested changes

2022-08-10 07:54 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
> +
Spostare in pn-common

2022-08-10 14:49 UTC, MTurraPpa approved these changes

2022-08-11 06:51 UTC, MTurraPpa approved these changes

2022-08-12 08:03 UTC, MTurraPpa approved these changes

2022-08-12 08:25 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
> +
fatto

2022-08-12 08:40 UTC, merged