Feature/pn 522
pagopa/pn-delivery-push pull request #165
Opened 2022-09-16 10:46 UTC by cFiorilloMediatica

2022-09-20 13:53 UTC, fabriziolana requested changes
sentiamoci

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/action/utils/DigitalWorkFlowUtilsTest.java
> +        Assertions.assertEquals(msg, exception.getMessage());
stesso discorso del codice di prima

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/exceptions/ExceptionHelperTest.java
> +//    private ExceptionHelper exceptionHelper;
cestinare, non c'è più

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/exceptions/GlobalErrorHandlerTest.java
> +
cestinare non serve più

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/externalclient/pnclient/safestorage/PnSafeStorageClientImplTestIT.java
> +        safeStorageClient.uploadContent(fileCreationRequest, fileCreationResponse, "sha");
si può lasciare solo l'assertdoesnotthrow, giusto?

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/DtoToEntityFutureActionMapperTest.java
> +    void dtoToEntity() {
implementare o togliere

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/EntityToDtoActionMapperTest.java
> +    void entityToDto() {
implementare o togliere

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/EntityToDtoFutureActionMapperTest.java
> +    void entityToDto() {
implementare o togliere

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/TimelineElementDetailsEntityConverterTest.java
> +    void transformFrom() {
implementare o togliere

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/delivery/PnDeliveryClientImplTest.java
> +    void updateStatus() {
implementare, anche gli altri metodi volendo

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/externalregistry/PnExternalRegistryClientImplTest.java
> +
implementare

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/mandate/PnMandateClientImplTest.java
> +    void listMandatesByDelegate() {
implementare

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/consumer/handler/NewNotificationEventHandlerTest.java
> +    void pnDeliveryNewNotificationEventConsumer() {
implementare

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/consumer/PnEventInboundServiceTest.java
> +    }
implementare

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/webhookspool/impl/WebhookActionsEventHandlerTest.java
> +    void handleEvent() {
implementare

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandlerTest.java
> +        Assertions.assertEquals(msg, exception.getMessage());
stesso discorso del codice di prima

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/service/mapper/RecipientMapperTest.java
> +        NotificationInt expected = NotificationTestBuilder.builder()
mancano le assertion

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/service/mapper/RecipientMapperTest.java
> +        SentNotification expected = getExternalNotification();
mancano le assertion

2022-09-20 13:53 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/utils/AuthUtilsTest.java
> +    }
implementare o togliere

2022-09-21 07:28 UTC, fabriziolana submitted a review, later dismissed

2022-09-22 07:01 UTC, marco-vit-pagopa commented
We identified new issues on unchanged lines of code. Navigate to the Amazon CodeGuru Reviewer console to view the recommendations to fix them.

2022-09-22 07:06 UTC, fabriziolana approved these changes

2022-09-22 07:50 UTC, fabriziolana approved these changes

2022-09-22 08:25 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/webhookspool/impl/WebhookActionsEventHandlerTest.java
> +    void handleEvent() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:36 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/consumer/handler/NewNotificationEventHandlerTest.java
> +    void pnDeliveryNewNotificationEventConsumer() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:36 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/timelinedao/dynamo/mapper/TimelineElementDetailsEntityConverterTest.java
> +    void transformFrom() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:36 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/EntityToDtoFutureActionMapperTest.java
> +    void entityToDto() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:37 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/EntityToDtoActionMapperTest.java
> +    void entityToDto() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:37 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/DtoToEntityFutureActionMapperTest.java
> +    void dtoToEntity() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 08:37 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/middleware/dao/actiondao/dynamo/mapper/DtoToEntityActionMapperTest.java
> +    void dtoToEntity() {
Aperta issue per implementazione https://pagopa.atlassian.net/browse/PN-2231

2022-09-22 13:50 UTC, fabriziolana approved these changes

2022-09-22 13:50 UTC, merged