Legal facts internal api #pn-2074
pagopa/pn-delivery-push pull request #173
Opened 2022-09-21 15:25 UTC by AndreaCimini90

2022-09-22 09:24 UTC, marco-vit-pagopa requested changes
Richiesti alcuni piccoli cambiamenti nell' OpenAPI

2022-09-22 10:33 UTC, AndreaCimini90 commented on docs/openapi/api-private-v1.yaml
> +        L'unico valore ammesso per il parametro _x-pagopa-pn-cx-type_ è `PA`
Cambiata la descrizione

2022-09-22 10:33 UTC, AndreaCimini90 commented on docs/openapi/api-private-v1.yaml
> +      $ref: 'https://raw.githubusercontent.com/pagopa/pn-auth-fleet/main/docs/openapi/authenticationParameters-v1.yaml#/components/parameters/cxIdAuthFleet'
Aggiunto riferimento all'ultimo commit id

2022-09-27 08:22 UTC, simonerondinella submitted a review, later dismissed

2022-09-27 08:29 UTC, simonerondinella approved these changes

2022-09-27 08:35 UTC, masciale89 requested changes

2022-09-27 08:35 UTC, masciale89 commented on docs/openapi/api-private-v1.yaml
> +        - $ref: '#/components/parameters/cxIdAuthFleet'
su delivery lo abbiamo chiamato recipientInternalId. Forse potrebbe essere corretto riportare il nome corretto per evitare confusione

2022-09-27 08:35 UTC, masciale89 commented on docs/openapi/api-private-v1.yaml
> +        - $ref: '#/components/parameters/cxIdAuthFleet'
stesso commento per il campo sopra

2022-09-27 09:32 UTC, masciale89 approved these changes
ok

2022-09-27 10:02 UTC, masciale89 approved these changes

2022-09-27 10:38 UTC, marco-vit-pagopa approved these changes

2022-09-27 10:41 UTC, merged