Feature/pn 2078
pagopa/pn-delivery-push pull request #177
Opened 2022-09-26 07:27 UTC by cFiorilloMediatica

2022-09-26 07:31 UTC, marco-vit-pagopa commented
We identified new issues on unchanged lines of code. Navigate to the Amazon CodeGuru Reviewer console to view the recommendations to fix them.

2022-09-26 07:31 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java
> +            } catch (Exception ex) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-09-26 07:31 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +        } catch (Exception exc) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-09-26 07:31 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +        } catch (Exception exc) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-09-26 07:31 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +        } catch (Exception exc) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-09-26 12:45 UTC, simonerondinella requested changes

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/AnalogWorkflowHandler.java
> -        if (status!= null) {
Eviterei di eliminare lo switch, ma aggiungerei la casistica di default mancante che dovrebbe risolvere anche il code smells

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/AnalogWorkflowHandler.java
> +    private ResponseStatusInt mapPaperStatusInResponseStatus(String paperStatus) {
Immagino che i whiteSpace e l'indentazione cambiata dipendando dall'ide, rimuovi quest'opzione

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/dto/timeline/TimelineEventId.java
> +        throw new UnsupportedOperationException("Must be implemented for each action type event ID");
Non mi è chiaro a cosa serve questa modifica? Direi di implementare la stessa logica delle altre exception aggiungendo il codice errore anche qui

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/DocumentComposition.java
> +            throw new PnInternalException("Processing template " + templateType, exc.getMessage());
Non è stato aggiunto il codice errore?

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/DocumentComposition.java
> +            throw new PnInternalException("Cannot get numberOfPages for pdf " + this.getClass(), ex.getMessage());
Non è stato aggiunto il codice errore?

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/dao/webhook/dynamo/mapper/EntityToStreamListDtoStreamMapper.java
>  @Component
Corretto aggiungere costruttore privato, ma eliminerei anche il @Component dal momento che della classe vengono utilizzati solo i metodi statici e non verrà mai iniettata

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/externalchannel/ExternalChannelSendClientImpl.java
> +            throw new PnInternalException("error sending PEC notification", ERROR_CODE_DELIVERYPUSH_SENDPECNOTIFICATIONFAILED);
- Nei casi in cui l'exception è presente va sempre utilizzato il costruttore di PnInternalException che prende anche il throwable come parametro di ingresso, altrimenti ci si perde l'informazione sull'exception.
- Aggiungere Log errore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/externalchannel/ExternalChannelSendClientImpl.java
> +            throw new PnInternalException("error sending EMAIL notification", ERROR_CODE_DELIVERYPUSH_SENDEMAILNOTIFICATIONFAILED);
- Nei casi in cui l'exception è presente va sempre utilizzato il costruttore di PnInternalException che prende anche il throwable come parametro di ingresso, altrimenti ci si perde l'informazione sull'exception.
- Aggiungere Log errore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/externalchannel/ExternalChannelSendClientImpl.java
> -            throw new PnInternalException("channel type not supported");
- Aggiungere Log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/externalchannel/ExternalChannelSendClientImpl.java
> +            throw new PnInternalException("channel type not supported", ERROR_CODE_DELIVERYPUSH_CHANNELTYPENOTSUPPORTED);
- Aggiungere Log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> -            throw new PnInternalException("cannot generate AAR pdf", ERROR_CODE_GENERATE_PDF_FAILED);
- Aggiungere Log errore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> -            throw new PnInternalException("cannot retreieve AAR pdf safestoragekey");
- Aggiungere Log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/NotificationUtils.java
> +        throw new PnInternalException("There isn't recipient in Notification", ERROR_CODE_DELIVERYPUSH_NO_RECIPIENT_IN_NOTIFICATION);
Aggiungere log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/DocumentComposition.java
> -            throw new PnInternalException( "Processing template " + templateType, exc );
Aggiungere log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/webhookspool/impl/WebhookActionsEventHandler.java
> +                    throw new PnInternalException("Error handling webhook event", ERROR_CODE_WEBHOOK_EVENTFAILED);
aggiunger log errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
>          } catch (PnInternalException e) {
Da rivedere questa parte di codice. Qui bisogna catturare e rilanciare l'interfaccia di exception generica che indica le exception generate da noi e rilanciarla semplicemente. Come viene già fatto

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> -            log.error("Exception legalUpdate", e);
loggare l'errore

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> -            log.error("Exception legalUpdate", e);
come sopra

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> -            log.error("Exception legalUpdate", e);
loggare l'exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> +            throw new PnInternalException("Legal update failed", ERROR_CODE_DELIVERYPUSH_UPDATEFAILED);
utilizzare costruttore con exception in ingresso

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> -            log.error("Exception legalUpdate", e);
come sopra

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> -            log.error("Exception legalUpdate", e);
loggare exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> +            throw new PnInternalException("Courtesy update failed", ERROR_CODE_DELIVERYPUSH_UPDATEFAILED);
utilizzare costruttore con exception in ingresso

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +            throw new PnInternalException(msg, ERROR_CODE_DELIVERYPUSH_SAVELEGALFACTSFAILED);
utilizzare costruttore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +            throw new PnInternalException(msg, ERROR_CODE_DELIVERYPUSH_SAVELEGALFACTSFAILED);
utilizzare costruttore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +            throw new PnInternalException(msg, ERROR_CODE_DELIVERYPUSH_SAVELEGALFACTSFAILED);
utilizzare costruttore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SaveLegalFactsServiceImpl.java
> +            throw new PnInternalException(msg, ERROR_CODE_DELIVERYPUSH_SAVENOTIFICATIONFAILED);
utilizzare costruttore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/TimeLineServiceImpl.java
> +                throw new PnInternalException("Exception in addTimelineElement - iun=" + notification.getIun() + " elementId=" + dto.getElementId(), ERROR_CODE_DELIVERYPUSH_ADDTIMELINEFAILED);
utilizzare costruttore con exception

2022-09-26 12:45 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/utils/StatusUtils.java
> +        throw new PnInternalException("situazione anomala", ERROR_CODE_DELIVERYPUSH_NOTIFICATIONSTATUSFAILED);
Aggiungere descrizione più specifica in inglese del problema

2022-09-26 12:45 UTC, simonerondinella commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/actionspool/impl/ActionsPoolImplTest.java
> +       // Mockito.verify(lastFutureActionPoolExecutionTimeDao, Mockito.times(1)).updateLastPollTime(instantTimeSlot);
Aggiungere qualche assertion a questo test case

2022-10-03 09:03 UTC, simonerondinella requested changes

2022-10-03 09:03 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> +            throw new PnInternalException("Paper update failed", ERROR_CODE_DELIVERYPUSH_UPDATEFAILED, e);
Questa parte di codice è da rivedere, rivediamola insieme:

"Da rivedere questa parte di codice. Qui bisogna catturare e rilanciare l'interfaccia di exception generica che indica le exception generate da noi e rilanciarla semplicemente. Come viene già fatto"

2022-10-03 09:03 UTC, simonerondinella commented on src/test/java/it/pagopa/pn/deliverypush/middleware/queue/producer/abstractions/actionspool/impl/ActionsPoolImplTest.java
> +        LockAssert.TestHelper.makeAllAssertsPass(true);
Sentiamoci, volevo capire meglio questa parte di codice

2022-10-03 15:59 UTC, masciale89 commented on src/main/java/it/pagopa/pn/deliverypush/middleware/responsehandler/ExternalChannelResponseHandler.java
> +        } catch (PnRuntimeException e) {
Come mai la PnRuntime?

2022-10-03 16:06 UTC, simonerondinella approved these changes

2022-10-03 16:07 UTC, merged