Feature/pn 2256
pagopa/pn-delivery-push pull request #186
Opened 2022-09-30 13:00 UTC by masciale89

2022-09-30 13:04 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SafeStorageServiceImpl.java
> +        } catch ( PnInternalException ex ) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-09-30 13:04 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AttachmentUtils.java
> +        } catch ( PnNotFoundException ex ) {
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**: While wrapping the caught exception into a custom one, information about the caught exception is being lost, including information about the stack trace of the exception.

**Fix**: If the caught exception object does not contain sensitive information, consider passing it as the &#34;rootCause&#34; or inner exception parameter to the constructor of the new exception before throwing the new exception. (Note that not all exception constructors support inner exceptions. Use a wrapper exception that supports inner exceptions.) 
[Learn more](https://www.ibm.com/support/pages/best-practice-catching-and-re-throwing-java-exceptions)

2022-10-03 07:41 UTC, simonerondinella requested changes

2022-10-03 07:41 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/StartWorkflowHandler.java
>          addTimelineElement( timelineUtils.buildRefusedRequestTimelineElement(notification, errors), notification);
Problem qui potrebbe essere null? Fare un check di problem diverso da null, se problem è null la lista di errors sarà vuota

2022-10-03 08:14 UTC, masciale89 commented on src/main/java/it/pagopa/pn/deliverypush/action/StartWorkflowHandler.java
>          addTimelineElement( timelineUtils.buildRefusedRequestTimelineElement(notification, errors), notification);
non dovrebbe essere null... aggiunto comunque il controllo per evitare NPE

2022-10-03 08:27 UTC, simonerondinella approved these changes

2022-10-03 08:30 UTC, merged