Feature/pn 2221 modifica atti opp
pagopa/pn-delivery-push pull request #191
Opened 2022-10-03 15:53 UTC by vincenzo-racca-pa

Questa PR comprende modifiche ai template HTML utilizzati per generare i PDF degli atti opponibili a terzi.

2022-10-03 15:54 UTC, vincenzo-racca-pa commented
Prima del merge, aspettare feedback finale di Alice Azzolini.

2022-10-04 14:53 UTC, simonerondinella requested changes

2022-10-04 14:53 UTC, simonerondinella commented on src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact.html
> +        </#if>
Un dubbio coma mai nell'else c'è 2020. e non solo il punto?

2022-10-04 15:16 UTC, vincenzo-racca-pa commented on src/main/resources/documents_composition_templates/PecDeliveryWorkflowLegalFact.html
> +        </#if>
perché mettendo solo il punto, il template inserisce uno spazio tra 2020 e il punto, quindi il risultato finale era "del 16 luglio 2020 ."

2022-10-05 07:10 UTC, simonerondinella approved these changes

2022-10-10 12:41 UTC, merged