Docs
pagopa/pn-delivery-push pull request #204
Opened 2022-10-10 14:33 UTC by MTurraPpa

2022-10-11 10:44 UTC, simonerondinella requested changes

2022-10-11 10:44 UTC, simonerondinella commented on docs/openapi/schemas-pn-timeline-v1.yaml
> +          * `PUBLIC_REGISTRY_RESPONSE` - Ricevuta la risposta dei registri pubblici alla richiesta di ottenimento dell'indirizzo SPECIALE
Come dicevamo l'indirizzo ottenuto dai PublicRegistry e GENERALE

2022-10-14 13:49 UTC, MTurraPpa commented on docs/openapi/schemas-pn-timeline-v1.yaml
> +          * `PUBLIC_REGISTRY_RESPONSE` - Ricevuta la risposta dei registri pubblici alla richiesta di ottenimento dell'indirizzo SPECIALE
modificato

2022-10-14 13:50 UTC, simonerondinella approved these changes

2022-10-20 16:17 UTC, merged