Feature/pn 1860
pagopa/pn-delivery-push pull request #255
Opened 2022-11-09 14:41 UTC by antoniopezzuto

2022-11-10 14:27 UTC, simonerondinella requested changes
Credo inoltre possa esserci bisogno per salvare l'entity come json su dynamo dell'attribute converter. Ad esempio "TimelineElementDetailsEntityConverter", non ne sono sicuro però, questo lo valutiamo meglio insieme

2022-11-10 14:27 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/action/startworkflowrecipient/StartWorkflowForRecipientHandler.java
> +        notification.getRecipients().get(recIndex).toBuilder().quickAccessLinkToken(details.getQuickAccessLinkToken());
Andrei qui a creare un metodo chiamato ad esempio "**unrichNotificationWithQuickAccessLinkToken**" o qualcosa di questo genere, in modo che da lettore ho una lettura più semplice e veloce di ciò che viene fatto, senza dover entrare nel dettaglio.
Eviterei inoltre di inserire il tutto in un unica riga di codice, in modo da individuare più semplicemente eventuali NullPointer ecc.

2022-11-11 09:00 UTC, antoniopezzuto commented
> 

Non è necessario, viene utilizzato il DocumentAttributeConverter<T>. Ho aggiunto un unit test per verificare la persistenza dei dettagli. 
Credo che il TimelineElementDetailsEntityConverter non viene utilizzato.

2022-11-11 09:08 UTC, simonerondinella approved these changes

2022-11-11 09:08 UTC, simonerondinella commented
> > 
> 
> Non è necessario, viene utilizzato il DocumentAttributeConverter. Ho aggiunto un unit test per verificare la persistenza dei dettagli. Credo che il TimelineElementDetailsEntityConverter non viene utilizzato.

2022-11-11 10:07 UTC, merged