add certificate configuration and use it for Rest Template creation
pagopa/pn-delivery-push pull request #36
Opened 2022-01-13 12:10 UTC by masciale89

2022-01-13 12:13 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/deliverypush/webhook/WebhookClientCertImpl.java
> +                throw new PnInternalException( "Unable to retrieve cert/key from env vars" );
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Exception [PnInternalException] is explicitly thrown on this line but is caught in the outer catch clause with generic exception on line [79].  Consider adding a catch clause of this specific exception in the outer try statement.

2022-01-18 08:47 UTC, MTurraPpa commented
Guardando il codice mi sembra che l'approccio migliore sia utilizzare un RestTemplateFactory che restituisce un RestTemplate in base alla configurazione, in modo da avere una sola implementazione della classe WebhookClient in cui la logica non cambia, è solo il restTemplate che può cambiare in base alla configurazione.

2022-01-18 16:45 UTC, MTurraPpa requested changes
Guardando il codice mi sembra che l'approccio migliore sia utilizzare un RestTemplateFactory che restituisce un RestTemplate in base alla configurazione, in modo da avere una sola implementazione della classe WebhookClient in cui la logica non cambia, è solo il restTemplate che può cambiare in base alla configurazione.

2022-01-19 14:43 UTC, MTurraPpa approved these changes

2022-01-19 14:45 UTC, MTurraPpa submitted a review, later dismissed

2022-01-21 08:26 UTC, MTurraPpa approved these changes

2022-01-24 07:22 UTC, MTurraPpa approved these changes

2022-01-24 07:23 UTC, merged