PN-3288 generate AUD_NT_AAR failure if AAR element is already present
pagopa/pn-delivery-push pull request #369
Opened 2023-01-26 10:23 UTC by cFiorilloMediatica

Per evitare di loggare un evento AAR SUCCESS a seguito del tentativo di generazione di un pdf per un evento AAR già presente in timeline, logghiamo un AAR FAILURE

2023-01-26 10:33 UTC, fabriziolana requested changes

2023-01-26 10:33 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +                throw new PnInternalException(
non va bene tirare eccezione per evitare di scrivere l'auditlog.

2023-01-26 11:50 UTC, fabriziolana requested changes

2023-01-26 11:50 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +        PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
la creazione dell'audit log va dentro l'if (timeline.isEmpty)

2023-01-26 11:50 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +        PnAuditLogBuilder auditLogBuilder = new PnAuditLogBuilder();
Inoltre, mi son dimenticato, ho creato il service AuditLogService, che si occupa di creare il logEvent e loggarlo.
Utile perchè in fase di test, si può mockare e controllare che il codice passi per generatesuccess/failure . Sarebbe da usare

2023-01-26 11:50 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +            logEvent.generateFailure("Exception on generation of AAR", e.getMessage()).log();
il try-catch a questo punto sarebbe da fare pure questo dentro all'if (timeline) (e nel caso di exception ovviamente rilanciarla).

2023-01-26 14:44 UTC, fabriziolana requested changes

2023-01-26 14:44 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +                logEvent.log();
la cosa bella del buildAuditLog è che non serve ripassare nel message iun e recindex, vengono aggiunti sempre proprio perchè li ho voluti esplicitare nel costruttore (apri l'Impl per farti un'idea di come funziona)
inoltre, esegue già il logEvent.log quindi non serve chiamarlo nuovamente.

2023-01-26 14:44 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/action/utils/AarUtilsTest.java
>      }
...e aggiungiamo nei test il check di generateSuccess o failure, così non abbiam fatto fatica per niente :)

//GIVEN
PnAuditLogEvent auditLogEvent = Mockito.mock(PnAuditLogEvent.class);
        Mockito.when( auditLogService.buildAuditLogEvent(Mockito.anyString(), Mockito.anyInt(), Mockito.eq(PnAuditLogEventType.AUD_PD_EXECUTE_RECEIVE), Mockito.anyString(), Mockito.any(), Mockito.any(), Mockito.any(), Mockito.any(), Mockito.any())).thenReturn(auditLogEvent);
        Mockito.when(auditLogEvent.generateSuccess()).thenReturn(auditLogEvent);

//WHEN
xxxxxxxxxxxx

// THEN
 Mockito.verify( auditLogEvent).generateSuccess();
        Mockito.verify( auditLogEvent).log();
        Mockito.verify( auditLogEvent, Mockito.never()).generateFailure(Mockito.any());

2023-01-26 14:48 UTC, fabriziolana commented
PS: risolvere anche la smell

2023-01-27 10:10 UTC, cFiorilloMediatica commented on src/test/java/it/pagopa/pn/deliverypush/action/utils/AarUtilsTest.java
>      }
Fatto

2023-01-27 10:10 UTC, cFiorilloMediatica commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +            logEvent.generateFailure("Exception on generation of AAR", e.getMessage()).log();
Fatto

2023-01-27 14:10 UTC, fabriziolana requested changes

2023-01-27 14:10 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/action/utils/AarUtilsTest.java
> -        Mockito.verify( auditLogEvent).log();
io nei miei  test avevo messo anche il check del metodo log(), perchè per come son fatti gli audit log, dopo il generateSuccess (o generateFailure), c'è anche il .log().
Se uno si dimentica il .log(), mi sa che non stampa nulla (il che sarebbe un errore che il test volevo beccasse), ti torna?

2023-01-27 14:32 UTC, cFiorilloMediatica commented on src/main/java/it/pagopa/pn/deliverypush/action/utils/AarUtils.java
> +    public void saveAARinSafeStorageAndAddTimelineElement(NotificationInt notification, Integer recIndex, String quickAccessToken) {
Fatto

2023-01-27 14:36 UTC, fabriziolana approved these changes

2023-01-27 14:39 UTC, merged