AAR mail and sms restyle - pn-4721
pagopa/pn-delivery-push pull request #471
Opened 2023-04-05 09:33 UTC by AndreaCimini90

2023-04-05 09:34 UTC, fabriziolana submitted a review, later dismissed

2023-04-06 09:57 UTC, MTurraPpa requested changes

2023-04-06 09:57 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
> +            log.debug(path + " is not found");
Se non viene trovato il logo che mi sembra una eventualità remota, essendo nel classpath dentro al Jar, penso che debba essere sollevato un vero e proprio error.

2023-04-06 09:57 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
> +                log.debug("error during file conversion", e);
Stesso discorso.

2023-04-06 09:57 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
> +                log.debug("error during file conversion", e);
Ho chiesto a Vincenzo di darti più specifiche

2023-04-06 14:41 UTC, vincenzo-racca-pa approved these changes

2023-04-06 15:29 UTC, MTurraPpa approved these changes

2023-04-07 09:18 UTC, MTurraPpa approved these changes

2023-04-07 10:15 UTC, merged