Feature/pn 3718
pagopa/pn-delivery-push pull request #482
Opened 2023-04-12 06:45 UTC by cFiorilloMediatica

2023-04-12 07:44 UTC, fabriziolana requested changes

2023-04-12 08:51 UTC, cFiorilloMediatica commented on src/main/java/it/pagopa/pn/deliverypush/legalfacts/LegalFactGenerator.java
>      public static final String FIELD_PN_FAQ_URL = "PNFaqURL";
In effetti non viene più usato, procedo con l'eliminazione

2023-04-12 09:52 UTC, fabriziolana approved these changes

2023-04-26 10:25 UTC, fabriziolana approved these changes

2023-04-26 10:40 UTC, merged