Feature/pn 5494
pagopa/pn-delivery-push pull request #512
Opened 2023-04-28 15:49 UTC by OscarEijsermans

2023-04-28 15:56 UTC, FeliceMente commented on docs/openapi/aws/api-delivery-push-WEB-aws.yaml
mi sembra strano che sia stata rimossa questa riga, forse un problema dovuto a parent non aggiornato?

2023-04-28 15:58 UTC, FeliceMente requested changes

2023-04-28 15:58 UTC, FeliceMente commented on docs/openapi/aws/api-delivery-push-WEB-aws.yaml
> -        identityValidationExpression: ^Bearer\s([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+)\.([a-zA-Z0-9_\-]+)$
mi sembra strano che sia stata rimossa questa riga, forse un problema dovuto a parent non aggiornato?

2023-04-28 16:58 UTC, FeliceMente commented on docs/openapi/aws/api-delivery-progresses-B2B-aws.yaml
>      api_key_openapi:
dopo aver aggiornato pn-parent si è portato queste modifiche... che andrebbero controllate

2023-05-02 09:24 UTC, fabriziolana commented on docs/openapi/aws/api-delivery-progresses-B2B-aws.yaml
>      api_key_openapi:
son stati tolti (evidentemente obsoleti)

2023-05-02 09:24 UTC, fabriziolana approved these changes

2023-05-02 09:47 UTC, fabriziolana approved these changes

2023-05-02 09:48 UTC, fabriziolana commented on docs/openapi/aws/api-delivery-progresses-B2B-aws.yaml
>      api_key_openapi:
sono state tolte erroneamente, ho fatto rollback

2023-05-02 10:01 UTC, fabriziolana approved these changes

2023-05-02 10:18 UTC, merged