feature/PN-5476
pagopa/pn-delivery-push pull request #533
Opened 2023-05-24 16:03 UTC by simonerondinella

2023-05-25 14:07 UTC, fabriziolana requested changes

2023-05-25 14:07 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SafeStorageServiceImpl.java
>          return safeStorageClient.getFile(fileKey, metadataOnly)
bisognerebbe wrappare pure qui con MDCUtils.addMDCToContextAndExecute

2023-05-25 14:07 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/SafeStorageServiceImpl.java
>          return safeStorageClient.updateFileMetadata(fileKey, updateFileMetadataRequest)
bisognerebbe wrappare pure qui con MDCUtils.addMDCToContextAndExecute

2023-05-25 14:33 UTC, simonerondinella commented on src/main/java/it/pagopa/pn/deliverypush/middleware/queue/consumer/handler/NationalRegistriesEventHandler.java
> +                log.debug("Handle message from {} with content {}", NationalRegistriesClient.CLIENT_NAME, message);
Lo faccio partire non appena ho disponibile lo iun

2023-05-25 15:05 UTC, fabriziolana submitted a review, later dismissed

2023-05-25 15:42 UTC, fabriziolana approved these changes

2023-05-25 16:07 UTC, fabriziolana submitted a review, later dismissed

2023-05-26 07:11 UTC, fabriziolana approved these changes

2023-05-26 07:22 UTC, merged