feature/PN-8970
pagopa/pn-delivery-push pull request #809
Opened 2024-01-16 13:07 UTC by ivanrosinapa

2024-01-16 13:10 UTC, fabriziolana requested changes

2024-01-16 13:10 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/NotificationProcessCostServiceImpl.java
>                      notificationViewDate = timelineElement.getTimestamp();
non è questo il timestamp da usare, ma quello specificato dentro al detail

    private Instant eventTimestamp;

2024-01-17 08:52 UTC, simonerondinella approved these changes

2024-02-07 07:55 UTC, fabriziolana approved these changes

2024-02-07 07:57 UTC, merged