Feature/pn 9706
pagopa/pn-delivery-push pull request #847
Opened 2024-02-12 09:39 UTC by fabriziolana

2024-02-12 11:25 UTC, fabriziolana commented on functions/versioningV1V2Webhook/src/test/handlers/consumeEventStreamHandler.test.js
> +            const responseBodyV23 = {
NB: il consume prevede un array di oggetti

2024-02-14 17:03 UTC, fdammassa requested changes

2024-02-14 17:03 UTC, fdammassa commented on functions/versioningV1V2Webhook/src/app/eventHandler.js
> +        console.log("PN_GENERIC_ERROR")
@fabriziolana nel caso di catch penso sia corretto loggare tutto l'errore

2024-02-14 17:03 UTC, fdammassa commented on scripts/aws/cfn/microservice.yml
> +        S3Key: !Sub "${MicroserviceBucketBaseKey}/functions_zip/VersioningV1V2Webhook.zip"
@fabriziolana il nome deve corrispondere a quello della cartella dentro `functions` , ossia `versioningV1V2Webhook` (v minuscola)

2024-02-15 07:38 UTC, fabriziolana commented on functions/versioningV1V2Webhook/src/app/eventHandler.js
> +        console.log("PN_GENERIC_ERROR")
done

2024-02-15 07:39 UTC, fabriziolana commented on scripts/aws/cfn/microservice.yml
> +        S3Key: !Sub "${MicroserviceBucketBaseKey}/functions_zip/VersioningV1V2Webhook.zip"
ah!

2024-02-15 07:53 UTC, fdammassa approved these changes

2024-02-15 08:05 UTC, merged