Feature/PN-10492
pagopa/pn-delivery-push pull request #892
Opened 2024-03-29 16:07 UTC by AnaNiagu

2024-03-29 16:45 UTC, fabriziolana requested changes

2024-03-29 16:45 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/middleware/externalclient/pnclient/paperchannel/PaperChannelSendClientImpl.java
> +        prepareRequest.setNotificationSentAt(Instant.now());
no, deve essere la paperChannelPrepareRequest.getNotificationInt().getSentAt

2024-03-29 16:45 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/deliverypush/service/impl/PaperChannelServiceImplTest.java
>          Mockito.verify(attachmentUtils, Mockito.never()).getNotificationAttachmentsAndPayments(any(), any(), anyInt(), anyBoolean(), any());
Qui aggiungere il verify del popolamento della data di sentAt.
dentro a newNotification (riga 444)  quando costruisce l'oggetto impostagli pure una data (no instant now, mettici na data fissa in modo che poi qui sotto riesci a testarla)

2024-04-02 14:54 UTC, fabriziolana approved these changes

2024-04-02 15:30 UTC, vincenzo-racca-pa approved these changes

2024-04-05 12:01 UTC, closed without merging