Feature/pn 10813
pagopa/pn-delivery-push pull request #917
Opened 2024-04-29 14:52 UTC by AnaNiagu

NB: necessità di ulteriore refactor dei metodi di AttachmentUtils (e Test) che devono essere privati

2024-04-29 15:19 UTC, fabriziolana requested changes

2024-04-29 15:19 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/action/startworkflow/notificationvalidation/AttachmentUtils.java
> +    private List<String> addNotificationF24PaymentsUrl(
chiamiamolo pure getNotificationF24PaymentsUrl

2024-04-29 15:19 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/PaperChannelServiceImpl.java
> +        return attachmentUtils.retrieveAttachments(notification, recIndex, attachmentUtils.retrieveSendAttachmentMode(notification, notificationChannelType), AttachmentUtils.F24_RESOLUTION_MODE.RESOL
qui il resolution_mode è quello della lista replaced24attachments

2024-04-30 13:54 UTC, vincenzo-racca-pa requested changes

2024-04-30 13:54 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/deliverypush/action/startworkflow/notificationvalidation/AttachmentUtils.java
> +    public enum F24_RESOLUTION_MODE{
Esternalizziamo questo enum in modo tale da aggiungere anche il javadoc che spieghi il significato di ogni valore. Inoltre rinominiamo in camelCase il nome dell'enum (F24ResolutionMode).

2024-05-02 07:52 UTC, vincenzo-racca-pa approved these changes

2024-05-02 10:43 UTC, merged