Feature/pn 10811 1 1 prepazione f24
pagopa/pn-delivery-push pull request #919
Opened 2024-05-02 07:06 UTC by EmanueleBonofiglio

2024-05-02 13:42 UTC, fabriziolana approved these changes

2024-05-03 07:24 UTC, fabriziolana approved these changes

2024-05-03 07:31 UTC, vincenzo-racca-pa requested changes

2024-05-03 07:31 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/deliverypush/service/impl/F24ServiceImpl.java
> +        pnF24Client.preparePDF(generateF24RequestTimelineElement.getElementId(),iun, cost);
Manca il .block alla chiamata. Questa rioga non verrà mai eseguita...

2024-05-03 08:15 UTC, vincenzo-racca-pa approved these changes

2024-05-03 09:32 UTC, merged