Bug/pn 8751
pagopa/pn-delivery-push pull request #955
Opened 2024-05-31 14:22 UTC by ivanrosinapa

2024-06-14 08:41 UTC, FeliceMente requested changes

2024-06-14 08:41 UTC, FeliceMente commented on scripts/aws/cfn/microservice.yml
> +          ATTEMPT_TIMEOUT: 7
ATTEMPT_TIMEOUT lo renderei più parlante facendo capire se si tratta di secondi, millisecondi o altro (ad esempio  ATTEMPT_TIMEOUT_SEC
 
 per entrambe le variabili, valuterei se renderle anche configurabili dallo yaml di configurazione

2024-06-14 08:41 UTC, FeliceMente requested changes

2024-06-14 08:41 UTC, FeliceMente commented on scripts/aws/cfn/microservice.yml
> +          ATTEMPT_TIMEOUT: 7
ATTEMPT_TIMEOUT lo renderei più parlante facendo capire se si tratta di secondi, millisecondi o altro (ad esempio  ATTEMPT_TIMEOUT_SEC
 
 per entrambe le variabili, valuterei se renderle anche configurabili dallo yaml di configurazione

2024-06-18 09:47 UTC, FeliceMente approved these changes

2024-06-19 07:34 UTC, EmanueleBonofiglio submitted a review, later dismissed

2024-07-25 13:51 UTC, EmanueleBonofiglio approved these changes

2024-07-25 14:56 UTC, merged